#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use BasicSteganography\Command\EncodeCommand;
use BasicSteganography\Command\DecodeCommand;

$application = new Application();

// commands
$application->add(new EncodeCommand());
$application->add(new DecodeCommand());

$application->run();
